### ISSUE TITLE
rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3

### ISSUE THREAD

**Issue by Willis814** [HKUST-Aerial-Robotics/PredRecon#14]
I successfully compiled the planner, but when I executed the "source devel/setup.zsh && roslaunch airsim_ros_pkgs airsim_node.launch" step, it prompted "rpclib: client error C0002: Function 'simGetImages' was called with an invalid number of arguments. Expected: 2, got: 3". I checked and found that this is generally because the AiSim client and server need to use the same version, and my airsim is version 1.8.1, so how could I solve the problem?
![image](https://github.com/HKUST-Aerial-Robotics/PredRecon/assets/74644896/575d0e6e-c71c-4bc5-952b-98b4805532f7)

**Comment by Chen-Albert-FENG** [comment]
You can follow the readme in [Planner](https://github.com/HKUST-Aerial-Robotics/PredRecon/tree/master/Planner) to reinstall the UE and AirSim. Notably, we only tested the project on UE 4.25.
