### ISSUE TITLE
May I download the repository by using the "Download ZIP" button directly?

### ISSUE THREAD

**Issue by Terry10086** [HKUST-Aerial-Robotics/PredRecon#3]
Thanks for your brilliant work! However, when I used the code below, 
`git clone git@github.com:HKUST-Aerial-Robotics/PredRecon.git`
it showed the error
```
Cloning into 'PredRecon'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
May I download the repository by using the "Download ZIP" button directly?

**Comment by Chen-Albert-FENG** [comment]
You can use 'git clone https://github.com/HKUST-Aerial-Robotics/PredRecon.git' in your terminal.
