### ISSUE TITLE
Px4 ctrl queries

### ISSUE THREAD

**Issue by EhrazImam** [HKUST-Aerial-Robotics/PredRecon#4]
Hi, Hope you are doing well.
thanks for great work!
I have been using px4 ctrl("https://github.com/ZJU-FAST-Lab/Fast-Drone-250/tree/master/src/realflight_modules/px4ctrl") and things are working fine but i was going through your repo and found out ("https://github.com/HKUST-Aerial-Robotics/PredRecon/tree/master/Planner/Code/src/px4ctrl") and i started comparing it i found there huge change in this and an additional file "https://github.com/HKUST-Aerial-Robotics/PredRecon/blob/master/Planner/Code/src/px4ctrl/src/hovthrkf.cpp", so what are changes from the previous one and i am planning to use it in real world so do i need to change anything apart from topic or is it just for simulation.

Thankyou

**Comment by Chen-Albert-FENG** [comment]
The px4 controller in this repo is for simulation (AirSim). You have to change it if you want to deploy our planner on the real drone.

**Comment by EhrazImam** [comment]
@Chen-Albert-FENG Thankyou
