### ISSUE TITLE
Is it possible to use spm model instead of spm_distill model to convert to .pt file?

### ISSUE THREAD

**Issue by ZhenyuShiUAV** [HKUST-Aerial-Robotics/PredRecon#6]
Hi, is it possible to use spm model instead of spm_distill model to convert to .pt file? When we load the spm model using the code 'lib_predictor.py', the line 'torch.jit.trace' gives error says:
```
Could not export Python function call '_Voxelization'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
```
Do you guys have any suggestions on solving this problem? Thank you.

**Comment by Chen-Albert-FENG** [comment]
Since the lib_torch does not support non-standard operators in jit transformation, we choose the distillation manner.
