### ISSUE TITLE
ply file to pcd file in PCN.zip

### ISSUE THREAD

**Issue by Willis814** [HKUST-Aerial-Robotics/PredRecon#8]
I have downloaded the PCN.zip and unzip it in the file folder of "data",should I convert all the ply files in PCN.zip to pcd files? If so, I wonder to know if there's a convenient way to convert all the files at once.
Thanks!

**Comment by Chen-Albert-FENG** [comment]
See https://github.com/HKUST-Aerial-Robotics/PredRecon/issues/2
